### ISSUE TITLE
Please contact me at rajbiz1@yahoo.com

### ISSUE THREAD

**Issue by rajbiz1** [vitaliy-kuzmich/postme#1]
Please contact me at rajbiz1@yahoo.com

I am an Iseries AS/400 devevloper for 22 years and wanted to move to Java. Had exposure to java syntax, JSP, Servlet, Java script.
wanted to learn by doing / reading an existing project. 
If you have an existing already developed web applicaiton that you can explain step by step on how that was developed and can share that app code, that will help me to understand how a professional web application should be created.
Thanks

**Comment by rajbiz1** [comment]
. Do you have any existing already developed professional web application that you can share with me and also explain step by step on how that was developed. 
AS I mentioned, I learned Java. JSP Servlet but do not have any practical experience which is what I am trying to gain with this proposal. Let me know how and what you can contribute for this request. Also, let me know what will be your charge for that..  Thank You

**Comment by vitaliy-kuzmich** [comment]
huh, man are you kidding? why should I share commercial sources to you ? Is
it some kind of joke? I will report you.

2017-09-13 17:07 GMT+03:00 rajbiz1 <notifications@github.com>:
